import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/Lenis/LenisProvider";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.variable} antialiased`}>
      {/* 
        1. Removed style={{ margin: 0, padding: 0 }} in favor of Tailwind's m-0 p-0 (or global CSS)
        2. Added suppressHydrationWarning to ignore extension/script style injections
        3. Removed stray whitespace {" "} inside <body>
      */}
      <body className="m-0 p-0" suppressHydrationWarning>
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}